#!/bin/bash

# Script spécifique pour déployer sur Render avec votre image DockerHub
set -e

IMAGE_NAME="brahim1205/appwoyofal:latest"

echo "🌐 Instructions de déploiement sur Render pour AppWoyofal"
echo "=================================================="
echo ""
echo "1. 📋 Connectez-vous à https://render.com"
echo ""
echo "2. 🆕 Créez un nouveau Web Service :"
echo "   - Cliquez sur 'New +' puis 'Web Service'"
echo "   - Sélectionnez 'Deploy an existing image from a registry'"
echo ""
echo "3. 🐳 Configuration de l'image Docker :"
echo "   - Image URL: $IMAGE_NAME"
echo "   - Port: 80"
echo "   - Health Check Path: /api/health"
echo ""
echo "4. 🗄️ Créez d'abord une base de données PostgreSQL :"
echo "   - Cliquez sur 'New +' puis 'PostgreSQL'"
echo "   - Nom: woyofal-postgres"
echo "   - Plan: Free (pour les tests)"
echo ""
echo "5. ⚙️ Variables d'environnement à configurer :"
echo "   DB_HOST=<host-de-votre-postgres-render>"
echo "   DB_PORT=5432"
echo "   DB_NAME=<nom-de-votre-db>"
echo "   DB_USER=<user-de-votre-db>"
echo "   DB_PASSWORD=<password-de-votre-db>"
echo ""
echo "6. 🚀 Déployez le service"
echo ""
echo "📝 Note: Render vous fournira automatiquement les valeurs de connexion"
echo "    à la base de données une fois celle-ci créée."
echo ""
echo "🔗 Votre API sera accessible à l'adresse :"
echo "   https://votre-service-name.onrender.com"
echo ""
echo "🧪 Tests de l'API :"
echo "   GET  https://votre-service-name.onrender.com/api/health"
echo "   POST https://votre-service-name.onrender.com/api/woyofal/acheter"
echo "   GET  https://votre-service-name.onrender.com/api/woyofal/verifier-compteur"
